@extends('layouts.admin')
@section('title',$project->exists?'Edit Project':'New Project')
@section('content')
<div class="mb-8"><p class="kicker">Project Editor</p><h1 class="text-3xl font-bold">{{ $project->exists ? 'Edit '.$project->name : 'Project baru' }}</h1></div>
<form method="POST" action="{{ $project->exists ? route('admin.projects.update',$project) : route('admin.projects.store') }}" enctype="multipart/form-data" class="max-w-5xl space-y-6">@csrf @if($project->exists) @method('PUT') @endif
@php($value = fn($field) => old($field, $project->{$field}))
<section class="bg-white p-6 shadow-sm sm:p-8"><h2 class="mb-6 text-lg font-bold">Basic Information</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="label">Name</label><input class="field" name="name" value="{{ $value('name') }}" required></div><div><label class="label">Slug</label><input class="field" name="slug" value="{{ $value('slug') }}" required></div><div><label class="label">Category</label><select class="field" name="project_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('project_category_id',$project->project_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div><label class="label">Eyebrow</label><input class="field" name="eyebrow" value="{{ $value('eyebrow') }}"></div><div class="sm:col-span-2"><label class="label">Short description</label><textarea class="field" name="short_description" rows="3" required>{{ $value('short_description') }}</textarea></div><div><label class="label">Project status</label><input class="field" name="project_status" value="{{ $value('project_status') }}" required></div><div><label class="label">Publishing status</label><select class="field" name="publishing_status"><option value="draft" @selected($value('publishing_status')==='draft')>Draft</option><option value="published" @selected($value('publishing_status')==='published')>Published</option><option value="archived" @selected($value('publishing_status')==='archived')>Archived</option></select></div><div><label class="label">Platform</label><input class="field" name="platform" value="{{ $value('platform') }}"></div><div><label class="label">Database</label><input class="field" name="database" value="{{ $value('database') }}"></div><div><label class="label">Year</label><input class="field" type="number" name="project_year" value="{{ $value('project_year') }}"></div><div><label class="label">Display order</label><input class="field" type="number" min="0" name="sort_order" value="{{ $value('sort_order') }}" required></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$project->is_featured))> Featured project</label></div></section>
<section class="bg-white p-6 shadow-sm sm:p-8"><h2 class="mb-6 text-lg font-bold">Case Study</h2><div class="grid gap-5">@foreach(['problem'=>'Problem','objective'=>'Objective','solution'=>'Solution','role'=>'My Role','business_process'=>'Business Process','architecture'=>'Architecture','challenges'=>'Challenges','result'=>'Result','lessons_learned'=>'Lessons Learned'] as $field=>$label)<div><label class="label">{{ $label }}</label><textarea class="field" name="{{ $field }}" rows="{{ in_array($field,['problem','solution']) ? 5 : 3 }}" @required(in_array($field,['problem','solution']))>{{ $value($field) }}</textarea></div>@endforeach</div></section>
<section class="bg-white p-6 shadow-sm sm:p-8"><h2 class="mb-6 text-lg font-bold">Technical & Media</h2><div class="grid gap-5 sm:grid-cols-2"><div><label class="label">Features (satu per baris)</label><textarea class="field" name="features_text" rows="8">{{ old('features_text',implode("\n",$project->features ?? [])) }}</textarea></div><div><label class="label">Technologies (satu per baris)</label><textarea class="field" name="technologies_text" rows="8">{{ old('technologies_text',implode("\n",$project->technologies ?? [])) }}</textarea></div><div><label class="label">Thumbnail</label><input class="field" type="file" name="thumbnail" accept="image/*"></div><div><label class="label">Architecture image</label><input class="field" type="file" name="architecture_image" accept="image/*"></div><div class="sm:col-span-2"><label class="label">Gallery images (maksimal 10 per upload)</label><input class="field" type="file" name="gallery_images[]" accept="image/*" multiple>@if($project->gallery)<p class="mt-2 text-xs text-slate-500">{{ count($project->gallery) }} gambar tersimpan.</p>@endif</div></div></section>
<section class="bg-white p-6 shadow-sm sm:p-8"><h2 class="mb-6 text-lg font-bold">SEO</h2><div class="grid gap-5"><div><label class="label">SEO title</label><input class="field" name="seo_title" value="{{ $value('seo_title') }}"></div><div><label class="label">Meta description</label><textarea class="field" name="meta_description" rows="3">{{ $value('meta_description') }}</textarea></div></div></section>
<div class="flex flex-wrap gap-3"><button class="btn-primary">Simpan project</button>@if($project->exists)<a class="btn-secondary" target="_blank" href="{{ route('projects.show',$project) }}">Preview ↗</a>@endif</div></form>
@if($project->exists)<form class="mt-10" method="POST" action="{{ route('admin.projects.destroy',$project) }}" onsubmit="return confirm('Hapus project ini secara permanen?')">@csrf @method('DELETE')<button class="text-sm font-bold text-red-600">Hapus project</button></form>@endif
@endsection
