@extends('layouts.app')
@section('title', $project->seo_title ?: $project->name.' | Brillian Ghulam')
@section('description', $project->meta_description ?: $project->short_description)
@section('content')
<section class="border-b border-slate-300 dark:border-slate-800"><div class="shell py-16 sm:py-24"><a href="{{ route('projects.index') }}" class="font-mono text-xs text-slate-500 hover:text-cyan">← KEMBALI KE PROJECT</a><p class="kicker mt-14">{{ $project->eyebrow }}</p><h1 class="display">{{ $project->name }}</h1><p class="lede mt-8">{{ $project->short_description }}</p></div><div class="shell grid border-t border-slate-300 dark:border-slate-800 sm:grid-cols-2 lg:grid-cols-5">@foreach ([['ROLE',$project->role ? 'System analysis & delivery' : '-'],['STATUS',$project->project_status],['PLATFORM',$project->platform],['DATABASE',$project->database],['YEAR',$project->project_year]] as $fact)<div class="border-b border-slate-300 py-5 sm:border-r sm:px-5 dark:border-slate-800"><dt class="font-mono text-[10px] text-slate-500">{{ $fact[0] }}</dt><dd class="mt-2 text-sm font-bold">{{ $fact[1] }}</dd></div>@endforeach</div></section>
<section class="section shell grid gap-12 lg:grid-cols-[.35fr_.65fr]"><div><p class="kicker">01 / Context</p><h2 class="text-3xl font-bold">Masalah yang diselesaikan</h2></div><div class="prose-copy text-lg"><p>{{ $project->problem }}</p>@if ($project->objective)<h3 class="mb-3 mt-10 text-sm font-bold uppercase tracking-wider text-cyan">Objective</h3><p>{{ $project->objective }}</p>@endif</div></section>
<section class="section bg-ink text-white"><div class="shell grid gap-12 lg:grid-cols-[.35fr_.65fr]"><div><p class="kicker">02 / Approach</p><h2 class="text-3xl font-bold">Solusi dan proses bisnis</h2></div><div><p class="text-xl leading-9 text-slate-200">{{ $project->solution }}</p>@if ($project->business_process)<div class="mt-10 border border-slate-700 p-6"><p class="font-mono text-[10px] text-cyan">PROCESS FLOW</p><p class="mt-4 leading-7 text-slate-300">{{ $project->business_process }}</p></div>@endif</div></div></section>
<section class="section shell"><div class="grid gap-12 lg:grid-cols-[.35fr_.65fr]"><div><p class="kicker">03 / System</p><h2 class="text-3xl font-bold">Arsitektur dan fitur</h2></div><div>@if ($project->architecture_path)<img class="mb-8 w-full rounded-2xl border border-slate-300 dark:border-slate-700" src="{{ '/storage/'.ltrim($project->architecture_path, '/') }}" alt="Diagram arsitektur {{ $project->name }}">@endif<p class="leading-8 text-slate-600 dark:text-slate-300">{{ $project->architecture }}</p><div class="mt-10 grid gap-px overflow-hidden rounded-xl border border-slate-300 bg-slate-300 dark:border-slate-700 dark:bg-slate-700 sm:grid-cols-2">@foreach ($project->features ?? [] as $feature)<div class="bg-paper p-5 font-semibold dark:bg-ink"><span class="mr-3 font-mono text-xs text-cyan">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span>{{ $feature }}</div>@endforeach</div><div class="mt-8 flex flex-wrap gap-2">@foreach ($project->technologies ?? [] as $technology)<span class="rounded-full border border-slate-300 px-3 py-2 font-mono text-xs dark:border-slate-700">{{ $technology }}</span>@endforeach</div></div></div></section>
<section class="section border-t border-slate-300 dark:border-slate-800"><div class="shell grid gap-8 md:grid-cols-3">@foreach ([['MY ROLE',$project->role],['CHALLENGES',$project->challenges],['RESULT',$project->result]] as $block)<article><p class="font-mono text-xs text-cyan">{{ $block[0] }}</p><p class="mt-5 leading-7 text-slate-600 dark:text-slate-300">{{ $block[1] }}</p></article>@endforeach</div>@if ($project->lessons_learned)<div class="shell mt-16"><div class="bg-cyan p-8 text-ink sm:p-12"><p class="font-mono text-xs font-bold">LESSONS LEARNED</p><p class="mt-5 max-w-4xl text-2xl font-bold leading-9">{{ $project->lessons_learned }}</p></div></div>@endif</section>
@if($project->gallery)<section class="section shell"><p class="kicker">04 / Gallery</p><div class="grid gap-5 md:grid-cols-2">@foreach($project->gallery as $image)<a href="{{ '/storage/'.ltrim($image, '/') }}" target="_blank"><img class="w-full rounded-2xl border border-slate-300 transition hover:scale-[1.01] dark:border-slate-700" loading="lazy" src="{{ '/storage/'.ltrim($image, '/') }}" alt="Screenshot {{ $project->name }} {{ $loop->iteration }}"></a>@endforeach</div></section>@endif
@if ($related->isNotEmpty())<section class="section shell"><p class="kicker">Related work</p><div class="grid gap-5 md:grid-cols-2">@foreach ($related as $item)<x-project-card :project="$item" :number="$loop->iteration" />@endforeach</div></section>@endif
@endsection
