@extends('layouts.app')
@section('title', 'Brillian Ghulam | System Analyst & ERP Implementor')
@section('description', $profile->tagline)
@section('content')
<section class="shell grid min-h-[calc(100vh-4.5rem)] items-center gap-12 py-16 lg:grid-cols-[1.35fr_.65fr]">
    <div><p class="kicker">Portfolio / Interactive CV</p><h1 class="display">Memahami proses.<br><span class="text-slate-400 dark:text-slate-500">Merancang sistem.</span><br>Menghasilkan solusi.</h1><p class="lede mt-8">{{ $profile->tagline }}</p><div class="mt-10 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('projects.index') }}">Lihat Project <span>↗</span></a><a class="btn-secondary" href="{{ route('resume') }}">Buka Resume</a></div></div>
    <aside class="relative border-l border-slate-300 pl-8 dark:border-slate-700"><span class="absolute -left-1 top-0 size-2 bg-cyan"></span>@if($profile->photo_path)<div class="relative mb-8 max-w-64"><div class="absolute -inset-2 translate-x-4 translate-y-4 border border-cyan"></div><img class="relative aspect-square w-full bg-blue-500 object-cover grayscale transition duration-500 hover:grayscale-0" src="{{ Storage::url($profile->photo_path) }}" alt="Foto {{ $profile->name }}"></div>@endif<p class="font-mono text-xs text-slate-500">CURRENT POSITION</p><p class="mt-3 text-2xl font-bold">{{ $profile->title }}</p><p class="mt-1 text-slate-500">PT. BEHAESTEX</p><dl class="mt-8 space-y-5 text-sm"><div><dt class="font-mono text-[10px] text-slate-500">FOCUS</dt><dd class="mt-1">Business Process · ERP · Data</dd></div><div><dt class="font-mono text-[10px] text-slate-500">LOCATION</dt><dd class="mt-1">{{ $profile->location }}</dd></div><div><dt class="font-mono text-[10px] text-slate-500">STATUS</dt><dd class="mt-1 text-emerald-600 dark:text-emerald-400">● Terbuka untuk diskusi profesional</dd></div></dl></aside>
</section>
<section class="border-y border-slate-300 bg-ink py-5 text-white dark:border-slate-800"><div class="shell flex flex-wrap gap-x-10 gap-y-3 font-mono text-xs uppercase tracking-wider text-slate-300"><span>Requirement Gathering</span><span>Business Process</span><span>ERP Implementation</span><span>Database Design</span><span>Automation</span></div></section>
<section class="section shell"><div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p class="kicker">01 / Selected Work</p><h2 class="text-4xl font-bold tracking-tight sm:text-5xl">Project yang menjelaskan<br>cara saya bekerja.</h2></div><a class="font-mono text-xs font-bold hover:text-cyan" href="{{ route('projects.index') }}">SEMUA PROJECT →</a></div><div class="mt-12 grid gap-5 lg:grid-cols-3">@foreach ($projects as $project)<x-project-card :project="$project" :number="$loop->iteration" />@endforeach</div></section>
<section class="section bg-white/60 dark:bg-white/[.025]"><div class="shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p class="kicker">02 / Profile</p><h2 class="text-4xl font-bold tracking-tight">Antara kebutuhan bisnis dan implementasi teknis.</h2></div><div><p class="lede">{{ $profile->summary }}</p><a class="btn-secondary mt-8" href="{{ route('about') }}">Tentang saya</a></div></div></section>
<section class="section shell"><p class="kicker">03 / Process</p><div class="grid gap-px border border-slate-300 bg-slate-300 dark:border-slate-700 dark:bg-slate-700 sm:grid-cols-2 lg:grid-cols-4">@foreach ([['01','Discover','Memahami user, masalah, constraint, dan proses yang berjalan.'],['02','Analyze','Memetakan proses, data, risiko, dan kebutuhan sistem.'],['03','Design','Merancang flow, database, interface, dan acceptance criteria.'],['04','Deliver','Menguji, melatih user, implementasi, dan mengevaluasi hasil.']] as $step)<div class="bg-paper p-7 dark:bg-ink"><span class="font-mono text-xs text-cyan">{{ $step[0] }}</span><h3 class="mt-8 text-xl font-bold">{{ $step[1] }}</h3><p class="mt-3 text-sm leading-6 text-slate-500">{{ $step[2] }}</p></div>@endforeach</div></section>
<section class="shell pb-24"><div class="bg-cyan p-8 text-ink sm:p-14"><p class="font-mono text-xs font-bold">LET'S SOLVE SOMETHING USEFUL</p><div class="mt-5 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><h2 class="max-w-3xl text-4xl font-bold leading-tight tracking-tight sm:text-5xl">Punya proses bisnis yang perlu dibuat lebih jelas dan efisien?</h2><a class="inline-flex shrink-0 items-center border border-ink px-6 py-3 font-bold hover:bg-ink hover:text-white" href="{{ route('contact') }}">Mulai percakapan →</a></div></div></section>
@endsection
