@extends('layouts.app')
@section('title', 'Brillian Ghulam | System Analyst & ERP Implementor')
@section('description', $profile->tagline)
@section('content')
<section class="relative overflow-hidden bg-white dark:bg-ink">
    <div class="absolute -right-32 top-10 size-[520px] rounded-full bg-orange-50 dark:bg-white/[.03]"></div><div class="absolute right-20 top-24 size-80 rounded-full border border-orange-100 dark:border-white/5"></div>
    <div class="shell relative grid min-h-[720px] items-center gap-12 py-16 lg:grid-cols-[1.08fr_.92fr] lg:py-24">
        <div class="relative z-10"><p class="kicker">System Analyst · ERP Implementor</p><h1 class="display">Solusi bisnis dimulai dari <span class="text-cyan">analisis yang tepat.</span></h1><p class="lede mt-7">{{ $profile->tagline }}</p><div class="mt-9 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('projects.index') }}">Lihat Project <span>↗</span></a><a class="btn-secondary" href="{{ route('contact') }}">Hubungi Saya</a></div><div class="mt-12 flex flex-wrap gap-x-9 gap-y-4 border-t border-slate-200 pt-7 text-sm dark:border-slate-700"><div><strong class="block text-2xl font-extrabold text-ink dark:text-white">3+</strong><span class="text-slate-500">Tahun pengalaman</span></div><div><strong class="block text-2xl font-extrabold text-ink dark:text-white">ERP</strong><span class="text-slate-500">Business process</span></div><div><strong class="block text-2xl font-extrabold text-ink dark:text-white">Data</strong><span class="text-slate-500">Analysis & automation</span></div></div></div>
        <div class="relative mx-auto w-full max-w-lg lg:mr-0"><div class="absolute -left-7 top-16 hidden h-28 w-1 rounded bg-cyan sm:block"></div><div class="absolute -right-4 -top-4 size-32 rounded-2xl bg-cyan/10"></div><div class="relative overflow-hidden rounded-[1.5rem] bg-ink shadow-2xl shadow-slate-900/20 sm:rounded-[2rem]">@if($profile->photo_path)<img class="aspect-[4/4.5] w-full object-cover object-[center_62%]" src="{{ '/storage/'.ltrim($profile->photo_path, '/') }}" alt="Foto {{ $profile->name }}">@endif<div class="absolute inset-x-3 bottom-3 rounded-xl bg-white/95 p-4 text-ink shadow-xl backdrop-blur sm:inset-x-5 sm:bottom-5 sm:rounded-2xl sm:p-5"><p class="text-[10px] font-bold uppercase tracking-wider text-cyan sm:text-xs">Current Role</p><p class="mt-1 text-base font-extrabold sm:text-xl">{{ $profile->title }}</p><p class="mt-1 text-xs text-slate-500 sm:text-sm">PT. BEHAESTEX · {{ $profile->location }}</p></div></div><div class="absolute -left-8 bottom-28 hidden rounded-xl bg-white p-4 shadow-xl sm:block dark:bg-slate-800"><span class="block text-2xl">✓</span><strong class="mt-1 block text-xs">Available for<br>collaboration</strong></div></div>
    </div>
</section>
<section class="bg-ink py-7 text-white"><div class="shell flex flex-wrap items-center justify-between gap-5 text-xs font-bold uppercase tracking-[.12em] text-slate-300"><span class="text-cyan">Core Expertise</span><span>Requirement Gathering</span><span>Business Process</span><span>ERP Implementation</span><span>Database & SQL</span><span>Automation</span></div></section>
<section class="section"><div class="shell"><div class="mx-auto max-w-3xl text-center"><p class="kicker justify-center">Keahlian utama</p><h2 class="section-title">Menghubungkan kebutuhan bisnis dengan implementasi teknologi.</h2><p class="mt-5 leading-8 text-slate-500">Pendekatan end-to-end untuk memahami masalah, merancang solusi, dan memastikan sistem dapat digunakan.</p></div><div class="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">@foreach ([['01','System Analysis','Requirement gathering, process mapping, functional specification, dan system design.'],['02','ERP Implementation','Testing, UAT, training, deployment, dan pendampingan implementasi.'],['03','Data & Database','SQL analysis, validation, reconciliation, reporting, dan database design.'],['04','Development','Web application, API integration, automation, dan operational tools.']] as $service)<article class="panel group p-7 transition hover:-translate-y-2"><span class="icon-box font-extrabold">{{ $service[0] }}</span><h3 class="mt-7 text-xl font-extrabold">{{ $service[1] }}</h3><p class="mt-3 text-sm leading-7 text-slate-500">{{ $service[2] }}</p><div class="mt-7 h-1 w-10 rounded bg-cyan transition-all group-hover:w-20"></div></article>@endforeach</div></div></section>
<section class="section bg-white dark:bg-white/[.025]"><div class="shell"><div class="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p class="kicker">Selected projects</p><h2 class="section-title">Case study yang menunjukkan<br>cara saya menyelesaikan masalah.</h2></div><a class="btn-secondary" href="{{ route('projects.index') }}">Lihat Semua Project →</a></div><div class="mt-12 grid gap-6 lg:grid-cols-3">@foreach ($projects as $project)<x-project-card :project="$project" :number="$loop->iteration" />@endforeach</div></div></section>
<section class="section"><div class="shell grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div class="relative"><div class="rounded-3xl bg-ink p-9 text-white sm:p-12"><p class="kicker text-orange-300">Tentang saya</p><h2 class="text-4xl font-extrabold leading-tight tracking-tight">Berada di antara kebutuhan user dan tim teknis.</h2><p class="mt-6 leading-8 text-slate-300">{{ $profile->summary }}</p><a class="mt-8 inline-flex items-center gap-2 font-bold text-cyan" href="{{ route('about') }}">Pelajari lebih lanjut →</a></div><div class="absolute -bottom-5 -right-5 -z-10 size-32 rounded-2xl bg-cyan/20"></div></div><div><p class="kicker">Work process</p><h2 class="section-title">Proses yang jelas menghasilkan implementasi yang lebih tepat.</h2><div class="mt-9 grid gap-6 sm:grid-cols-2">@foreach ([['01','Discover','Memahami user, masalah, constraint, dan proses yang berjalan.'],['02','Analyze','Memetakan proses, data, risiko, dan kebutuhan sistem.'],['03','Design','Merancang flow, database, interface, dan acceptance criteria.'],['04','Deliver','Menguji, melatih user, implementasi, dan evaluasi.']] as $step)<div class="flex gap-4"><span class="text-xl font-extrabold text-cyan">{{ $step[0] }}</span><div><h3 class="font-extrabold">{{ $step[1] }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $step[2] }}</p></div></div>@endforeach</div></div></div></section>
@endsection
